FILTERS = {
    "sedimentation": {
        "name": "Sedimentation",
        "short": "SEDIMENT",
        "desc": "Coarse screen & settling tank.\nRemoves large particles by gravity.",
        "removal": {
            "turbidity": (0.40, 0.60),
            "bacteria": (0.10, 0.20),
            "heavy_metals": (0.03, 0.07),
        },
        "ph_adjust": 0,
        "adds_chlorine": 0,
        "water_loss": 0.02,
        "cost": 50,
        "energy": 0,
        "cost_label": "Very Low",
        "energy_label": "None",
        "color": 4,
        "uses_max": 999,
        "degradation": 0.0,
    },
    "slow_sand": {
        "name": "Slow Sand Filter",
        "short": "SLOWSAND",
        "desc": "Bio-layer (schmutzdecke) filtration.\n1-3 log bacteria removal. No power needed.",
        "removal": {
            "turbidity": (0.90, 0.99),
            "bacteria": (0.90, 0.99),
            "pesticides": (0.10, 0.20),
            "tds": (0.03, 0.07),
        },
        "ph_adjust": 0,
        "adds_chlorine": 0,
        "water_loss": 0.03,
        "cost": 100,
        "energy": 0,
        "cost_label": "Low",
        "energy_label": "None",
        "color": 9,
        "uses_max": 999,
        "degradation": 0.0,
    },
    "rapid_sand": {
        "name": "Rapid Sand Filter",
        "short": "RAPIDSND",
        "desc": "Fast mechanical sand filtration.\nGood turbidity removal, moderate bacteria.",
        "removal": {
            "turbidity": (0.80, 0.95),
            "bacteria": (0.60, 0.90),
            "tds": (0.03, 0.07),
        },
        "ph_adjust": 0,
        "adds_chlorine": 0,
        "water_loss": 0.03,
        "cost": 150,
        "energy": 1,
        "cost_label": "Low",
        "energy_label": "Low",
        "color": 9,
        "uses_max": 999,
        "degradation": 0.0,
    },
    "gac": {
        "name": "Activated Carbon (GAC)",
        "short": "CARBON",
        "desc": "Granular activated carbon adsorption.\nExcellent for pesticides, taste, odor.",
        "removal": {
            "pesticides": (0.90, 0.99),
            "chlorine": (0.95, 0.99),
            "turbidity": (0.50, 0.70),
            "heavy_metals": (0.30, 0.60),
            "tds": (0.10, 0.20),
        },
        "ph_adjust": 0,
        "adds_chlorine": 0,
        "water_loss": 0.01,
        "cost": 300,
        "energy": 1,
        "cost_label": "Medium",
        "energy_label": "Low",
        "color": 5,
        "uses_max": 10,
        "degradation": 0.05,
    },
    "reverse_osmosis": {
        "name": "Reverse Osmosis (RO)",
        "short": "R.O.",
        "desc": "High-pressure membrane filtration.\nRemoves nearly everything but wastes water.",
        "removal": {
            "tds": (0.94, 0.99),
            "heavy_metals": (0.95, 0.99),
            "nitrates": (0.85, 0.95),
            "bacteria": (0.999, 0.9999),
            "pesticides": (0.95, 0.99),
            "hardness": (0.95, 0.99),
            "turbidity": (0.95, 0.99),
        },
        "ph_adjust": -0.5,
        "adds_chlorine": 0,
        "water_loss": 0.30,
        "cost": 800,
        "energy": 3,
        "cost_label": "High",
        "energy_label": "High",
        "color": 12,
        "uses_max": 999,
        "degradation": 0.0,
    },
    "ion_exchange": {
        "name": "Ion Exchange Resin",
        "short": "ION-EX",
        "desc": "Swaps harmful ions for harmless ones.\nGreat for hardness. No bacteria removal.",
        "removal": {
            "hardness": (0.95, 0.99),
            "nitrates": (0.80, 0.95),
            "heavy_metals": (0.70, 0.95),
        },
        "ph_adjust": 0,
        "adds_chlorine": 0,
        "water_loss": 0.05,
        "cost": 400,
        "energy": 1,
        "cost_label": "Medium",
        "energy_label": "Low",
        "color": 14,
        "uses_max": 8,
        "degradation": 0.06,
    },
    "uv": {
        "name": "UV Disinfection",
        "short": "UV",
        "desc": "Ultraviolet light kills bacteria.\nNeeds low turbidity (<5 NTU) to work well!",
        "removal": {
            "bacteria": (0.999, 0.9999),
        },
        "ph_adjust": 0,
        "adds_chlorine": 0,
        "water_loss": 0.0,
        "cost": 350,
        "energy": 2,
        "cost_label": "Medium",
        "energy_label": "Medium",
        "color": 13,
        "uses_max": 999,
        "degradation": 0.0,
        "uv_turbidity_sensitive": True,
    },
    "chlorination": {
        "name": "Chlorination",
        "short": "CHLOR",
        "desc": "Chemical disinfection with chlorine.\nKills bacteria, adds residual protection.",
        "removal": {
            "bacteria": (0.999, 0.9999),
        },
        "ph_adjust": -0.3,
        "adds_chlorine": 0.35,
        "water_loss": 0.0,
        "cost": 100,
        "energy": 0,
        "cost_label": "Low",
        "energy_label": "None",
        "color": 11,
        "uses_max": 999,
        "degradation": 0.0,
    },
    "lime_treatment": {
        "name": "Lime/Soda Ash (pH Up)",
        "short": "LIME pH+",
        "desc": "Adds lime to raise pH.\nAlso reduces hardness and metals.",
        "removal": {
            "hardness": (0.30, 0.50),
            "heavy_metals": (0.15, 0.30),
        },
        "ph_adjust": 1.2,
        "adds_chlorine": 0,
        "water_loss": 0.02,
        "cost": 80,
        "energy": 0,
        "cost_label": "Low",
        "energy_label": "None",
        "color": 7,
        "uses_max": 999,
        "degradation": 0.0,
    },
    "aeration": {
        "name": "Aeration (Cl- / pH+)",
        "short": "AERATE",
        "desc": "Bubbles air through water.\nStrips chlorine, raises pH, removes odor.",
        "removal": {
            "chlorine": (0.50, 0.70),
            "pesticides": (0.10, 0.25),
        },
        "ph_adjust": 0.4,
        "adds_chlorine": 0,
        "water_loss": 0.01,
        "cost": 60,
        "energy": 1,
        "cost_label": "Low",
        "energy_label": "Low",
        "color": 6,
        "uses_max": 999,
        "degradation": 0.0,
    },
}

FILTER_ORDER = [
    "sedimentation", "slow_sand", "rapid_sand", "gac",
    "reverse_osmosis", "ion_exchange", "uv", "chlorination",
    "lime_treatment", "aeration",
]
